Add fix for kubelet bug
Sometime the kubelet stopped with the message "kubelet stopped posting
node status" which happens because of too many dead http2 connections.

This is a workaround until this issue will be resolved (probably the
first kubernetes version with go v1.16)

Signed-off-by: Phillip Stagnet <p.stagnet@syseleven.de>

diff --git a/pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws-external.yaml b/pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws-external.yaml
--- a/pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws-external.yaml
+++ b/pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws-external.yaml
@@ -8,6 +8,20 @@ passwd:
 
 systemd:
   units:
+    - name: kubelet-restart.service
+      enabled: true
+      contents: |
+        [Unit]
+        Description=Restarts kubelet on use of closed network connection error
+        Requires=kubelet.service
+        After=kubelet.service
+
+        [Service]
+        ExecStart=/opt/kubelet-restart.sh
+
+        [Install]
+        WantedBy=multi-user.target
+
     - name: update-engine.service
       mask: true
     - name: locksmithd.service
@@ -151,6 +165,25 @@ systemd:
 
 storage:
   files:
+    - path: /opt/kubelet-restart.sh
+      filesystem: root
+      mode: 0755
+      contents:
+        inline: |
+          #!/bin/bash
+
+          while true; do
+              output=$(journalctl -u kubelet -n 1 | grep "use of closed network connection")
+              if [[ $? != 0 ]]; then
+                  echo "Error not found in logs"
+              elif [[ $output ]]; then
+                  echo "Restart kubelet"
+                  systemctl restart kubelet
+              fi
+
+              # Runs every 10 minutes
+              sleep 600
+          done
 
     - path: "/etc/systemd/journald.conf.d/max_disk_use.conf"
       filesystem: root
diff --git a/pkg/userdata/sles/testdata/vsphere-proxy.yaml b/pkg/userdata/sles/testdata/vsphere-proxy.yaml
--- a/pkg/userdata/sles/testdata/vsphere-proxy.yaml
+++ b/pkg/userdata/sles/testdata/vsphere-proxy.yaml
@@ -8,6 +8,38 @@ ssh_authorized_keys:
 - "ssh-rsa AAABBB"
 
 write_files:
+- path: "/opt/kubelet-restart.sh"
+  permissions: "0755"
+  content: |
+    #!/bin/bash
+
+    while true; do
+        output=$(journalctl -u kubelet -n 1 | grep "use of closed network connection")
+        if [[ $? != 0 ]]; then
+            echo "Error not found in logs"
+        elif [[ $output ]]; then
+            echo "Restart kubelet"
+            systemctl restart kubelet
+        fi
+
+        # Runs every 10 minutes
+        sleep 600
+    done
+
+- path: "/etc/systemd/system/kubelet-restart.service"
+  permissions: "0644"
+  content: |
+    [Unit]
+    Description=Restarts kubelet on use of closed network connection error
+    Requires=kubelet.service
+    After=kubelet.service
+
+    [Service]
+    ExecStart=/opt/kubelet-restart.sh
+
+    [Install]
+    WantedBy=multi-user.target
+
 - path: "/etc/environment"
   content: |
     PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
@@ -119,6 +151,7 @@ write_files:
     systemctl enable --now kubelet
     systemctl enable --now --no-block kubelet-healthcheck.service
     systemctl enable --now --no-block docker-healthcheck.service
+    systemctl enable --now --no-block kubelet-restart.service
 
 - path: "/opt/bin/supervise.sh"
   permissions: "0755"
